- name: install NFS sever
  apt:
    name: nfs-kernel-server

- name: create NFS dirs
  file:
    path: '{{item}}'
    state: directory
  loop:
    - /var/opt/gitlab/.ssh 
    - /var/opt/gitlab/gitlab-rails/uploads 
    - /var/opt/gitlab/gitlab-rails/shared 
    - /var/opt/gitlab/gitlab-ci/builds 
    - /var/opt/gitlab/git-data

- name: config of nfs
  shell: "echo \"{{item}}\" >> /etc/exports"
  loop:
    - "/var/opt/gitlab/.ssh *(rw,sync,no_root_squash,no_all_squash)"
    - "/var/opt/gitlab/gitlab-rails/uploads *(rw,sync,no_root_squash,no_all_squash)"   
    - "/var/opt/gitlab/gitlab-rails/shared *(rw,sync,no_root_squash,no_all_squash)"
    - "/var/opt/gitlab/gitlab-ci/builds *(rw,sync,no_root_squash,no_all_squash)"
    - "/var/opt/gitlab/git-data *(rw,sync,no_root_squash,no_all_squash)"

- name: restart nfs server
  systemd:
    name: nfs-kernel-server
    state: restarted
    enabled: yes
