- name: install dependencies packages
  apt:
    name: "{{item}}"
  loop:
    - haproxy
    - keepalived

- name: add config to hosts
  shell: "echo {{item}} >> /etc/hosts"
  loop:
    - "{{haproxyAddress}}\tinstance-gitlab-08"
    - "{{firstGitlabAddress}}\tinstance-gitlab-06"
    - "{{gitlabAddress}}\tinstance-gitlab-07"

- name: haproxy config
  shell: "echo 'ENABLED=1' >> /etc/default/haproxy"

# round-robin load balance
- name: more haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: allow acess to shared IP address
  shell: "echo 'net.ipv4.ip_nonlocal_bind=1' >> /etc/sysctl.conf"

- name: reload config change
  shell: "sysctl -p"

- name: keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: stop sshd
  service:
    name: sshd
    state: stopped

- name: restart haproxy
  service:
    name: haproxy
    state: restarted

- name: start and enable keepalived
  service:
    name: keepalived
    state: started
    enabled: yes
