- name: install necessary packages
  apt:
    name: '{{item}}'
  loop:
    - postgresql
    - libpq-dev
    - python-psycopg2
    - postgresql-9.5-repmgr

- name: Add pg_hba.conf line to permit access from network
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/9.5/main/pg_hba.conf"

- name: Add postgresql.conf for config
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/9.5/main/postgresql.conf" 

- name: Ensure service is enabled and started
  service:
    name: postgresql
    state: restarted
    enabled: yes

- name: create user
  become_user: postgres
  postgresql_user:
    name: gitlab
    password: '{{password}}'
    role_attr_flags: SUPERUSER,CREATEROLE,CREATEDB,REPLICATION

- name: create database
  become_user: postgres
  postgresql_db:
    name: '{{item}}'
    encoding: 'unicode'
    owner: gitlab
    state: present
  loop:
    - gitlabhq_production
    - repmgr 

- name: ensure user has access to database
  become_user: postgres
  postgresql_user: 
    db: '{{item}}'
    name: gitlab
    priv: ALL
  loop:
    - gitlabhq_production
    - repmgr

- name: add extension to database
  become_user: postgres
  postgresql_ext:
    name: pg_trgm
    db: gitlabhq_production
    state: present

- name: Add repmgr.conf for config
  template:
    src: repmgr.conf.j2
    dest: "/etc/repmgr.conf" 

- name: Add config to repmgrd
  copy:
    content: "REPMGRD_ENABLED=yes\nREPMGRD_CONF=\"/etc/repmgr.conf\"" 
    dest: /etc/default/repmgrd

- name: fix bug
  file:
    src: /usr/lib/postgresql/9.5/bin/pg_ctl
    dest: /usr/bin/pg_ctl
    state: link 

- name: restart repmgrd
  service:
    name: repmgrd
    state: restarted
