- name: postfix install pre-config
  shell: "echo \"{{item}}\" | debconf-set-selections"
  loop:
    - "postfix postfix/main_mailer_type select internetsite"
    - "postfix postfix/mailname string $hostname.localdomain"

- name: install dependencies packages
  apt:
    name: '{{item}}'
  loop:
    - curl
    - openssh-server
    - ca-certificates
    - postfix
    - glusterfs-client
    - postgresql-client
    - policycoreutils
    - rsync
    - attr

- name: create dir
  file:
    path: "/gitlab-data"
    state: directory

- name: add to hosts
  lineinfile:
    path: /etc/hosts
    line: "{{groups['first-gfs'][0]}}\tgluster0\n{% for host in groups['gfs'] %}{{host}}\tgluster{{loop.index}}\n{% endfor %}"

- name: mount folders
  mount:
    path: "/gitlab-data"
    src: "{{groups['first-gfs'][0]}}:/gitlab"
    opts: "defaults,_netdev,backupvolfile-server={{groups['gfs']}}"
    dump: 0
    passno: 0
    fstype: glusterfs
    state: mounted

- name: pre-install for gitlab
  shell: 
    cmd: "curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash"
    chdir: /tmp

- name: install gitlab
  apt:
    name: gitlab-ce

- name: gitlab configs
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb

- name: reconfigure gitlab
  shell: gitlab-ctl reconfigure

  #- name: stop gitlab
  #shell: gitlab-ctl stop

  #- name: start gitaly
  #shell: gitlab-ctl start gitaly

  #- name: setup gitlab
  #shell: DISABLE_DATABASE_ENVIRONMENT_CHECK=1 force=yes gitlab-rake gitlab:setup

  #- name: restart gitlab
  #shell: gitlab-ctl restart

  #- name: reconfigure gitlab
  #shell: gitlab-ctl reconfigure

- name: fetch secrets
  fetch:
    src: /etc/gitlab/gitlab-secrets.json
    dest: /tmp
