- name: postfix install pre-config
  shell: "echo \"{{item}}\" | debconf-set-selections"
  loop:
    - "postfix postfix/main_mailer_type select internetsite"
    - "postfix postfix/mailname string $hostname.localdomain"

- name: install dependencies packages
  apt:
    name: '{{item}}'
  loop:
    - curl
    - openssh-server
    - ca-certificates
    - postfix
    - nfs-common
    - postgresql-client
    - policycoreutils
    - rsync

- name: create NFS dirs
  file:
    path: '{{item}}'
    state: directory
  loop:
    - /var/opt/gitlab/.ssh 
    - /var/opt/gitlab/gitlab-rails/uploads 
    - /var/opt/gitlab/gitlab-rails/shared 
    - /var/opt/gitlab/gitlab-ci/builds 
    - /var/opt/gitlab/git-data

- name: mount folders
  mount:
    path: '{{item}}'
    src: "{{nfsAddress}}:{{item}}"
    opts: "defaults,soft,rsize=1048576,wsize=1048576,noatime,nofail,lookupcache=positive"
    dump: 0
    passno: 2
    fstype: nfs4
    state: mounted
  loop:
    - "/var/opt/gitlab/.ssh"
    - "/var/opt/gitlab/gitlab-rails/uploads"
    - "/var/opt/gitlab/gitlab-rails/shared"
    - "/var/opt/gitlab/gitlab-ci/builds"
    - "/var/opt/gitlab/git-data"

- name: pre-install for gitlab
  shell: 
    cmd: "curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash"
    chdir: /tmp

- name: install gitlab
  apt:
    name: gitlab-ce

- name: gitlab configs
  copy:
    content: "external_url 'http://{{gitlabAddress}}'\nhigh_availability['mountpoint'] = '/var/opt/gitlab/git-data'\ngitlab_rails['db_adapter'] = 'postgresql'\ngitlab_rails['db_encoding'] = 'unicode'\ngitlab_rails['db_database'] = 'gitlabhq_production'\ngitlab_rails['db_pool'] = 10\ngitlab_rails['db_username'] = 'gitlab'\ngitlab_rails['db_password'] = '{{postgrePassword}}'\ngitlab_rails['db_host'] = '{{postgreAddress}}'\ngitlab_rails['db_port'] = 5432\nredis['master_name'] = 'instance-gitlab-02'\ngitlab_rails['redis_port'] = 6379\nredis['master_password'] = '{{redisPassword}}'\ngitlab_rails['redis_socket'] = nil\ngitlab_rails['redis_sentinels'] = [\n    {'host' => '{{redisMasterAddress}}', 'port' => 26379},\n    {'host' => '{{redisSlaveAddress1}}', 'port' => 26379},\n    {'host' => '{{redisSlaveAddress2}}', 'port' => 26379}\n]\npostgresql['enable'] = false\nredis['enable'] = false\nnginx['enable'] = true\nnginx['redirect_http_to_https'] = true\nuser['uid'] = 9000\nuser['gid'] = 9000\nweb_server['uid'] = 9001\nweb_server['gid'] = 9001\nregistry['uid'] = 9002\nregistry['gid'] = 9002" 
    dest: /etc/gitlab/gitlab.rb

- name: reconfigure gitlab
  shell: gitlab-ctl reconfigure

- name: fetch secrets
  fetch:
    src: /etc/gitlab/gitlab-secrets.json
    dest: /tmp
