- name: postfix install pre-config
  shell: "echo \"{{item}}\" | debconf-set-selections"
  loop:
    - "postfix postfix/main_mailer_type select internetsite"
    - "postfix postfix/mailname string $hostname.localdomain"

- name: install dependencies packages
  apt:
    name: '{{item}}'
  loop:
    - curl
    - openssh-server
    - ca-certificates
    - postfix
    - glusterfs-client
    - postgresql-client
    - policycoreutils
    - rsync
    - attr

- name: create dir
  file:
    path: "/gitlab-data"
    state: directory

- name: add to hosts
  lineinfile:
    path: /etc/hosts
    line: "{{groups['first-gfs'][0]}}\tgluster0\n{% for host in groups['gfs'] %}{{host}}\tgluster{{loop.index}}\n{% endfor %}"

- name: mount folders
  mount:
    path: "/gitlab-data"
    src: "{{groups['first-gfs'][0]}}:/gitlab"
    opts: "defaults,_netdev,backupvolfile-server={{groups['gfs']}}"
    dump: 0
    passno: 0
    fstype: glusterfs
    state: mounted

- name: add to /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: "/gitlab-data/git-data /var/opt/gitlab/git-data none bind 0 0\n/gitlab-data/.ssh /var/opt/gitlab/.ssh none bind 0 0\n/gitlab-data/uploads /var/opt/gitlab/gitlab-rails/uploads none bind 0 0\n/gitlab-data/shared /var/opt/gitlab/gitlab-rails/shared none bind 0 0\n/gitlab-data/builds /var/opt/gitlab/gitlab-ci/builds none bind 0 0\n"

- name: pre-install for gitlab
  shell: 
    cmd: "curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash"
    chdir: /tmp

- name: install gitlab
  apt:
    name: gitlab-ce

- name: gitlab configs
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb

- name: copy secrets
  copy:
    src: "/tmp/{{groups['first-gitlab'][0]}}/etc/gitlab/gitlab-secrets.json"
    dest: /etc/gitlab/gitlab-secrets.json

- name: prevent database migrations
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch

- name: reconfigure gitlab
  shell: gitlab-ctl reconfigure
