- name: install redis
  apt:
    name: redis-server

- name: config files
  template:
    src: '{{item[0]}}' 
    dest: '{{item[1]}}'
  loop:
    - ["redis.conf.j2", "/etc/redis/redis.conf"]
    - ["sentinel.conf.j2", "/etc/redis/sentinel.conf"]

- name: restart redis
  shell: "redis-cli shutdown"

- name: start sentinel
  shell: "redis-server /etc/redis/sentinel.conf --sentinel &"
