- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: gcp
      vars:
        gcp_zone: us-central1-c
        gcp_region: us-central1
        gcp_project: sdb-gitlab
        gcp_cred_kind: serviceaccount
        gcp_cred_file: ../credentials.json
        source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20181030
        disk_size: 12
        disks:
          - disk-gitlab-01
          - disk-gitlab-02
          - disk-gitlab-03
          - disk-gitlab-04
          - disk-gitlab-05
          - disk-gitlab-06
        addresses:
          - addr-gitlab-01
          - addr-gitlab-02
          - addr-gitlab-03
          - addr-gitlab-04
          - addr-gitlab-05
          - addr-gitlab-06
        instances:
          - { index: 1, tag: postgre, gcp_machine_type: n1-standard-1}
          - { index: 2, tag: redis-master, gcp_machine_type: n1-standard-1}
          - { index: 3, tag: redis-slave, gcp_machine_type: g1-small}
          - { index: 4, tag: redis-slave, gcp_machine_type: g1-small}
          - { index: 5, tag: nfs, gcp_machine_type: n1-standard-1}
          - { index: 6, tag: gitlab, gcp_machine_type: n1-standard-2}

- hosts: all
  become: yes
  roles:
    - { role: users, payload: users.yml }

- hosts: postgre
  become: yes
  roles:
    - {
       role: postgre,
       password: "{{ lookup('passwordstore', 'ansible/postgre create=true length=8') }}"
      }

- hosts: redis-master
  become: yes
  roles:
    - {
       role: redis-master,
       password: "{{ lookup('passwordstore', 'ansible/redis create=true length=8') }}",
       redisMasterAddress: "{{ groups['redis-master'][0] }}"
      }

- hosts: redis-slave
  become: yes
  roles:
    - {
       role: redis-slave,
       password: "{{ lookup('passwordstore', 'ansible/redis create=true length=8') }}",
       redisMasterAddress: "{{ groups['redis-master'][0] }}"
      }

- hosts: nfs
  become: yes
  roles:
    - {role: nfs}

- hosts: gitlab
  become: yes
  roles:
    - {
       role: gitlab,
       nfsAddress: "{{ groups['nfs'][0] }}",
       gitlabAddress: "{{ groups['gitlab'][0] }}",
       postgreAddress: "{{ groups['postgre'][0] }}",
       postgrePassword: "{{ lookup('passwordstore', 'ansible/postgre create=true length=8') }}",
       redisPassword: "{{ lookup('passwordstore', 'ansible/redis create=true length=8') }}",
       redisMasterAddress: "{{ groups['redis-master'][0] }}",
       redisSlaveAddress1: "{{ groups['redis-slave'][0] }}",
       redisSlaveAddress2: "{{ groups['redis-slave'][1] }}"
      }
