- name: install necessary packages
  apt:
    name: '{{item}}'
  loop:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: Uncomment listen addresses configuration
  replace:
    path: "/etc/postgresql/9.5/main/postgresql.conf"
    regexp: '^#listen_addresses'
    replace: listen_addresses
    #notify:
    #- restart postgresql

- name: Replace listen addresses
  replace:
    path: "/etc/postgresql/9.5/main/postgresql.conf"
    regexp: "^listen_addresses\\s+=\\s+'(.*)'"
    replace: "listen_addresses = '*'"
    #notify:
    #- restart postgresql

- name: Add pg_hba.conf line to permit access from network
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/9.5/main/pg_hba.conf"
    #notify:
    #- restart postgresql

- name: Ensure service is enabled and started
  service:
    name: postgresql
    state: restarted
    enabled: yes

- name: create user
  become_user: postgres
  postgresql_user:
    name: gitlab
    password: '{{password}}'
    role_attr_flags: SUPERUSER,CREATEROLE,CREATEDB,REPLICATION

- name: create database
  become_user: postgres
  postgresql_db:
    name: gitlabhq_production
    encoding: 'UTF-8'
    owner: gitlab
    state: present

- name: ensure user has access to database
  become_user: postgres
  postgresql_user: 
    db: gitlabhq_production
    name: gitlab
    priv: ALL

- name: add extension to database
  become_user: postgres
  postgresql_ext:
    name: pg_trgm
    db: gitlabhq_production
    state: present
