- name: postfix install pre-config
  shell: "echo \"{{item}}\" | debconf-set-selections"
  loop:
    - "postfix postfix/main_mailer_type select internetsite"
    - "postfix postfix/mailname string $hostname.localdomain"

- name: install dependencies packages
  apt:
    name: '{{item}}'
  loop:
    - curl
    - openssh-server
    - ca-certificates
    - postfix
    - nfs-common
    - postgresql-client
    - policycoreutils
    - rsync

- name: create NFS dirs
  file:
    path: '{{item}}'
    state: directory
  loop:
    - /var/opt/gitlab/.ssh 
    - /var/opt/gitlab/gitlab-rails/uploads 
    - /var/opt/gitlab/gitlab-rails/shared 
    - /var/opt/gitlab/gitlab-ci/builds 
    - /var/opt/gitlab/git-data

- name: mount folders
  mount:
    path: '{{item}}'
    src: "{{nfsAddress}}:{{item}}"
    opts: "defaults,soft,rsize=1048576,wsize=1048576,noatime,nofail,lookupcache=positive"
    dump: 0
    passno: 2
    fstype: nfs4
    state: mounted
  loop:
    - "/var/opt/gitlab/.ssh"
    - "/var/opt/gitlab/gitlab-rails/uploads"
    - "/var/opt/gitlab/gitlab-rails/shared"
    - "/var/opt/gitlab/gitlab-ci/builds"
    - "/var/opt/gitlab/git-data"

- name: pre-install for gitlab
  shell: 
    cmd: "curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash"
    chdir: /tmp

- name: install gitlab
  apt:
    name: gitlab-ce

- name: gitlab configs
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    #\nnginx['redirect_http_to_https'] = true

- name: more gitlab configs
  shell: "echo \"{{item[0]}}['{{item[1]}}']='{{item[2]}}'\" >> /etc/gitlab/gitlab.rb"
  loop:
    - ["gitlab_shell","secret_token","{{gitlabSecrets.gitlab_shell.secret_token}}"]
    - ["gitlab_rails","otp_key_base","{{gitlabSecrets.gitlab_rails.otp_key_base}}"]
    - ["gitlab_rails","secret_key_base","{{gitlabSecrets.gitlab_rails.secret_key_base}}"]
    - ["gitlab_rails","db_key_base","{{gitlabSecrets.gitlab_rails.db_key_base}}"]

- name: prevent database migrations
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch

- name: reconfigure gitlab
  shell: gitlab-ctl reconfigure
